language: node_js
node_js: "8"
sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install
install:
script:
  - yarn build
cache:
  yarn: true
  directories:
    - ~/.npm
git:
  depth: 1
deploy:
  provider: surge
  project: ./public/
  domain: data-driven-forms.surge.sh 
  skip_cleanup: true
